### ISSUE TITLE
How to run code in win10 system?

### ISSUE THREAD

**Issue by LoveIsAGame** [JosephKJ/OWOD#1]
Thank you very much for your excellent work. I wonder if I can run the code under win10 system? If you can, can you provide installation documents for me?

**Comment by JosephKJ** [comment]
Hi @LoveIsAGame, 

Thank you for your interest and kind words. We do support only Ubuntu. But, you can probably give it a try as PyTorch is officially supported on Windows 10. 

Thanks,
Joseph

**Comment by LoveIsAGame** [comment]
thanks， i will  try and tell you the results.
