### ISSUE TITLE
KeyError: 'Non-existent config key: OWOD'

### ISSUE THREAD

**Issue by ccblublu** [JosephKJ/OWOD#10]
first thank for your excellent job 
but an error occurred when i tried to reproduce your code:

Traceback (most recent call last):
  File "tools/train_net.py", line 172, in <module>
    args=(args,),
  File "/media/chen/299D817A2D97AD94/detectron2/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "tools/train_net.py", line 134, in main
    cfg = setup(args)
  File "tools/train_net.py", line 126, in setup
    cfg.merge_from_file(args.config_file)
  File "/media/chen/299D817A2D97AD94/detectron2/detectron2/config/config.py", line 55, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/chen/.conda/envs/detectron/lib/python3.6/site-packages/fvcore/common/config.py", line 123, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/chen/.conda/envs/detectron/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/chen/.conda/envs/detectron/lib/python3.6/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))

KeyError: 'Non-existent config key: OWOD'

i think i have installed detectron2 successful
look forward to your reply

**Comment by deepakksingh** [comment]
Even I'm facing the same issue while trying to train on iOD/all_20_train.yaml

**Comment by ccblublu** [comment]
@deepakksingh  i guess it's because of the version of the referenced detectron2 package 
but i m not sure 
it seems connot build the right cfg from OWOD, are there any changes to the files in the detectorn2 folder and the installed detectron2 package?
@JosephKJ

**Comment by JosephKJ** [comment]
Hi @ccblublu, @deepakksingh  : There are many changes to files within detectorn2 folder. The whole repository should be used as is. It is not designed to work off-the-shelf with other detectron2 versions. 

Further, can you share the exact command that you used?

**Comment by deepakksingh** [comment]
Hi @JosephKJ, 
I used the following command:
```python
python tools/train_net.py --num-gpus=4 --config-file=./configs/OWOD/iOD/all_20_train.yaml
```

**Comment by JosephKJ** [comment]
And, have you build detectron 2 from this repo?

**Comment by deepakksingh** [comment]
I already have detectron2 built, so I did not build from this repo.
Silly doubt, If I build from this repo, will my pre-built build be affected?

**Comment by JosephKJ** [comment]
@deepakksingh : That is the reason. You need to build detectron2 from this repo. 

If I build from this repo, will my pre-built build be affected?: Yes. Please use another python env to sandbox your projects.

**Comment by deepakksingh** [comment]
Thank you @JosephKJ. I will try that out.

**Comment by deepakksingh** [comment]
I created a new environment and built it using, (I was at OWOD directory which already has the setup.py)
```bash
python -m pip install -e ./
```
I had to install some packages, and I also set the DETECTRON2_DATASETS path, but when I run the following command,
```
python tools/train_net.py --num-gpus=4 --config-file=./configs/OWOD/iOD/all_20_train.yaml
```
It is not able to use the detectron2 apis to download the WEIGHTS and throws this.
```
AssertionError: Checkpoint detectron2://ImageNetPretrained/MSRA/R-50.pkl not found!

```

**Comment by deepakksingh** [comment]
I noticed that there is a Deprecation Warning:
```
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

Command Line Args: Namespace(config_file='./configs/OWOD/iOD/all_20_train.yaml', dist_url='tcp://127.0.0.1:50712', eval_only=False, machine_rank=0, num_gpus=4, num_machin
es=1, opts=[], resume=False)
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 
```

**Comment by JosephKJ** [comment]
This is the fix: https://github.com/Majiker/BalancedMetaSoftmax-InstanceSeg/issues/3#issuecomment-778738124

**Comment by LoveIsAGame** [comment]
@deepakksingh    I met the same problem as you. Have you solved it?  if yes. Could you please tell me the detailed solution process?Thanks!

**Comment by deepakksingh** [comment]
Yes, I'm able to resolve the issue.
I had to re-build detectron2, as mentioned in the INSTALL.md, The `reliability` package  was missing and I had to downgrade fvcore as mentioned in the following issue.
> This is the fix: [Majiker/BalancedMetaSoftmax-InstanceSeg#3 (comment)](https://github.com/Majiker/BalancedMetaSoftmax-InstanceSeg/issues/3#issuecomment-778738124)

**Comment by LoveIsAGame** [comment]
@deepakksingh And I solved the problem!Thank you very much!

**Comment by Hrqingqing** [comment]
> @deepakksingh And I solved the problem!Thank you very much!

Hello,I can‘t understand the meaning of re-build,in INSTALL.md,there are "Build Detectron2 from Source" and "Install Pre-Built Detectron2 (Linux only)",Which one should I follow. 
Looking forward to your reply.

**Comment by shyam671** [comment]
I build the repo using the following steps:

Step1: Download the repo. Run the command: python -m pip install -e [Name of the folder]. (Ex- python -m pip install -e OWOD)
Step2: Install the missing package [in my case: shortuuid, reliability].

Hope this helps!!

**Comment by haleqiu** [comment]
> Hi @ccblublu, @deepakksingh : There are many changes to files within detectorn2 folder. The whole repository should be used as is. It is not designed to work off-the-shelf with other detectron2 versions.
> 
> Further, can you share the exact command that you used?

sounds like the instruction of installation is out-of-date? Anyone update the instruction?

**Comment by deepakksingh** [comment]
@haleqiu I recently built it again. What issues are you facing?

**Comment by Jiyang-Zheng** [comment]
```
Traceback (most recent call last):
  File "/home/.conda/envs/owod/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/scratch1/BW/Projects/OWOD/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/scratch1/BW/Projects/OWOD/tools/train_net.py", line 132, in main
    cfg = setup(args)
  File "/scratch1/BW/Projects/OWOD/tools/train_net.py", line 127, in setup
    default_setup(cfg, args)
  File "/scratch1/zhe030/BW/Projects/OWOD/detectron2/engine/defaults.py", line 132, in default_setup
    logger.info("Environment info:\n" + collect_env_info())
  File "/scratch1/BW/Projects/OWOD/detectron2/utils/collect_env.py", line 136, in collect_env_info
    msg = " - invalid!" if not os.path.isdir(CUDA_HOME) else ""
  File "/home/.conda/envs/owod/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

```
I am experiencing this issue after all instruction above.

**Comment by deepakksingh** [comment]
@Jiyang-Zheng, Could you check whether CUDA_HOME is set?
Looking at the traceback it seems to be missing.

**Comment by Jiyang-Zheng** [comment]
@deepakksingh  Thanks dude. I have now solved the issue. Appreciate for your advice.

For anyone interested
 https://github.com/facebookresearch/detectron2/issues/2254
will do the fix. 

Cheers

**Comment by martinriven** [comment]
I encountered the same problem. I install detectron2 in the OWOD file , and install reliability package, but I still got the same error, can anyone help? (P.S. I downgraded fvcore but got the error said fvcore should >= 0.1.2, so I chose not to downgrade fvcore)

**Comment by martinriven** [comment]
> @haleqiu I recently built it again. What issues are you facing?

I followed your steps, but got `AssertionError: cuda is not available. Please check your installation.` my cuda is 11.2, and I tried the pytorch maching cuda 10.2 and 11.2, but still got this error. Any advice?

**Comment by martinriven** [comment]
can you explain how to deal with it? The issue you mentioned just put forward the problem, I just can't find how to solve it
