### ISSUE TITLE
Cofusing about incremental object detection.

### ISSUE THREAD

**Issue by jinweiisgreat** [JosephKJ/OWOD#100]
Thank you for your nice paper. But I don't know how to conduct incremental object detection. 

- According to the open world setting. When the model labels sufficient unknown classes, the model will forward these unknown classes to humans to identify, right?
- So, between task2 and task3, we need a human to manually add the new classes identified by task2 to the model, right?
- In my understanding, the whole experiment process can be divided into two parts. The first stage is detecting new classes and the second stage is adding new classes to the model, right?
- So, there will be a process of human-computer interaction between two tasks, right?

Sorry, I am new to the field of incremental learning. Just confusing about this. Maybe I missed something in the article.

知道的也可以一起讨论，
就是我不清楚增量环节是怎么做的，task1是voc，这我们都知道；task2是识别多出来的类，那么在task3之前是不是要手动把task2的unknown给标注出来。这个手动标注是怎么做的？所以说整个实验是分成了4个task，在每一个task之间是暂停程序，人为的加标签进去？这么看起来挺繁琐的。

我不知道啊，我看实验部分也没说，是不是我看漏了？

**Comment by lcb1225** [comment]
你好，可以交流一下吗？

**Comment by JosephKJ** [comment]
In-between tasks, we assume that the identified unknowns (automatically identified by the OWOD model), would be labeled by an annotator. 

Please let me know whether this clarifies.

**Comment by jinweiisgreat** [comment]
> 你好，可以交流一下吗？

加一下微信，1204498144

**Comment by JiuqingDong** [comment]
> 
Hi, jinwei, Is this your Wechat ID? May I discuss some questions with you? I check your profile, and I am also interest in OWOD. Looking forward to your reply.

**Comment by jinweiisgreat** [comment]
> > 
> 
> Hi, jinwei, Is this your Wechat ID? May I discuss some questions with you? I check your profile, and I am also interest in OWOD. Looking forward to your reply.

yes
