### ISSUE TITLE
rodeo

### ISSUE THREAD

**Issue by Taleword2** [JosephKJ/OWOD#101]
大家有复现成功rodeo: replay for online object detection这篇论文的吗，训练过程是什么样的啊，感觉很乱。

**Comment by Zed-Yuan** [comment]
你好，我最近在研究复现owod项目，请问能向你请教一下吗

**Comment by JosephKJ** [comment]
我们不支持 RODEO

**Comment by JosephKJ** [comment]
Our code doesnot support RODEO. Please see [here](https://github.com/manoja328/rodeo).
