### ISSUE TITLE
files on google drive can not download

### ISSUE THREAD

**Issue by JiuqingDong** [JosephKJ/OWOD#109]
Hi, I can not download the JpegImages and owod_backup. Could you give some suggestions to obtain it? By the way, is the 'owod_backup' necessary?

**Comment by JiuqingDong** [comment]
it kept reminding me that I had exceeded the download limit and could not download it,Could you please share the data again?

**Comment by JiuqingDong** [comment]
> Hi, I can not download the JpegImages and owod_backup. Could you give some suggestions to obtain it? By the way, is the 'owod_backup' necessary?

I solve this problem. Thank you for your work.

**Comment by JiuqingDong** [comment]
By the way, is the 'owod_backup' necessary?

**Comment by YH-2023** [comment]
> 

How did you handle it?

**Comment by JiuqingDong** [comment]
> 
'owod_backup'不是必须的。
如果提示你超出下载配额，你就开个google drive会员，然后复制文件到自己的硬盘。
图片文件下载总是中断，网上有一些解决办法，你可以参考一下这个解决方案。下载一个Internet Download Manager加速器https://blog.csdn.net/weixin_45525272/article/details/128633007

然后我看到你是中国人，所以用了中文。

**Comment by YH721** [comment]
> > 
> 
> 'owod_backup'不是必须的。 如果提示你超出下载配额，你就开个google drive会员，然后复制文件到自己的硬盘。 图片文件下载总是中断，网上有一些解决办法，你可以参考一下这个解决方案。下载一个Internet Download Manager加速器https://blog.csdn.net/weixin_45525272/article/details/128633007
> 
> 然后我看到你是中国人，所以用了中文。

谢谢哦！

**Comment by JiuqingDong** [comment]
@YH721 你是研究员还是研究生？如果你对OWOD也有兴趣的话，我们可以交流一下。

https://drive.google.com/file/d/1gq8tzOnHuXKzO4rlgYyKE8cpvU_TRjvh/view?usp=share_link

https://drive.google.com/file/d/1gq8tzOnHuXKzO4rlgYyKE8cpvU_TRjvh/view?usp=share_link
不用开会员也可以，从这里下载也行。但你要用Internet Download Manager加速器，30天免费试用

**Comment by YH721** [comment]
> @YH721 你是研究员还是研究生？如果你对OWOD也有兴趣的话，我们可以交流一下。
> 
> https://drive.google.com/file/d/1gq8tzOnHuXKzO4rlgYyKE8cpvU_TRjvh/view?usp=share_link
> 
> https://drive.google.com/file/d/1gq8tzOnHuXKzO4rlgYyKE8cpvU_TRjvh/view?usp=share_link 不用开会员也可以，从这里下载也行。但你要用Internet Download Manager加速器，30天免费试用

研究生，我的联系方式：750216519

**Comment by YH721** [comment]
> > @YH721 你是研究员还是研究生？如果你对OWOD也有兴趣的话，我们可以交流一下。
> > https://drive.google.com/file/d/1gq8tzOnHuXKzO4rlgYyKE8cpvU_TRjvh/view?usp=share_link
> > https://drive.google.com/file/d/1gq8tzOnHuXKzO4rlgYyKE8cpvU_TRjvh/view?usp=share_link 不用开会员也可以，从这里下载也行。但你要用Internet Download Manager加速器，30天免费试用
> 
> 研究生，我的联系方式：750216519

这里我试过了，
![image](https://user-images.githubusercontent.com/59163676/222706838-1011c9dc-6af3-4142-9183-cc395e317a61.png)

**Comment by YH721** [comment]
> > @YH721 你是研究员还是研究生？如果你对OWOD也有兴趣的话，我们可以交流一下。
> > https://drive.google.com/file/d/1gq8tzOnHuXKzO4rlgYyKE8cpvU_TRjvh/view?usp=share_link
> > https://drive.google.com/file/d/1gq8tzOnHuXKzO4rlgYyKE8cpvU_TRjvh/view?usp=share_link 不用开会员也可以，从这里下载也行。但你要用Internet Download Manager加速器，30天免费试用
> 
> 研究生，我的联系方式：7502

> @YH721 你是研究员还是研究生？如果你对OWOD也有兴趣的话，我们可以交流一下。
> 
> https://drive.google.com/file/d/1gq8tzOnHuXKzO4rlgYyKE8cpvU_TRjvh/view?usp=share_link
> 
> https://drive.google.com/file/d/1gq8tzOnHuXKzO4rlgYyKE8cpvU_TRjvh/view?usp=share_link 不用开会员也可以，从这里下载也行。但你要用Internet Download Manager加速器，30天免费试用

这种方式我也用了，代理也开了，会出现下面的情况
![image](https://user-images.githubusercontent.com/59163676/222707730-851239f7-fcbf-4d2b-baea-1a2906aa0835.png)

**Comment by JiuqingDong** [comment]
@YH721 这种情况可能是因为你在国内网络受限吧。你翻墙应该可以下载。或者我用百度网盘上传一下吧，方便你下载。
这是我的微信：18317136107，可以交流一下

**Comment by functail** [comment]
> @YH721 你是研究员还是研究生？如果你对OWOD也有兴趣的话，我们可以交流一下。
> 
> https://drive.google.com/file/d/1gq8tzOnHuXKzO4rlgYyKE8cpvU_TRjvh/view?usp=share_link
> 
> https://drive.google.com/file/d/1gq8tzOnHuXKzO4rlgYyKE8cpvU_TRjvh/view?usp=share_link 不用开会员也可以，从这里下载也行。但你要用Internet Download Manager加速器，30天免费试用

大佬，求问：OWOD改动了哪些Detectron2的源代码，刚接触OWOD还不知道如何下手

**Comment by JiuqingDong** [comment]
>求问：OWOD改动了哪些Detectron2的源代码，刚接触OWOD还不知道如何下手

仔细读论文第四章，分别改动了loss，ROIhead， energy。这些代码在detectron2.modeling里面。

Bytheway，我已弃坑
