### ISSUE TITLE
The order of config files execution

### ISSUE THREAD

**Issue by ShuoYang-1998** [JosephKJ/OWOD#11]
Hi, Thanks for your excellent work!
I found the config files in ./configs/OWOD/ folder and the data split files in ./datasets/OWOD_imagesets/ are extremely  confusing. What does t#_train_with_unk.yaml mean? What does t#_ft.yaml mean? Should I have to run t#_val.yaml before t#_test.yaml? Can you provide a config file execution order if I want to reproduce the ORE results? E.g., t1_train.yaml->t1_val.yaml->t1_test.yaml->t2_train.yaml ...... 
It would be very appreciated if you can release several run.sh that consists of all training schedules in the paper.

Thanks!

**Comment by JosephKJ** [comment]
What does t#_train_with_unk.yaml mean?
>> You can ignore this. This is to train with unknown labelled so. This is used to report the 'Oracle' result in Table 2.

 t1_train.yaml->t1_val.yaml->t1_test.yaml-
>> Thats correct. 

run.sh
>> I will definitely do. Please allow some time.

**Comment by JosephKJ** [comment]
Please find the updated [run.sh](https://github.com/JosephKJ/OWOD/blob/master/run.sh)
