### ISSUE TITLE
2023年了，还有人复现成功吗。

### ISSUE THREAD

**Issue by lshssel** [JosephKJ/OWOD#129]
最近刚被安排做这个方向，这两年cvpr和iccv上也都有相关文章，打算水一篇。看了大家前面的提问，似乎很难复现出来

**Comment by dxjdx** [comment]
> 最近刚被安排做这个方向，这两年cvpr和iccv上也都有相关文章，打算水一篇。看了大家前面的提问，似乎很难复现出来

我也是做这个方向的的   咱们可以加个v   交流交流   我的是：dxj_l_xb

**Comment by Saun-Hu** [comment]
2024年了。有人复现成功了吗。。。

**Comment by GMR523** [comment]
这一系列的文章几乎都很难复现 建议撤退 包括后面的

**Comment by 1928908522** [comment]
训练了task1的模型，按文章说后面的task2,task3,task4中的类别应当检测出来是“unknow”，但是跑了几张图片都没跑出来，咋回事。要么就是单纯的目标检测结果，要么就是啥都没有检测出来的原图

**Comment by weileng2023** [comment]
2025年了我还在复现
