### ISSUE TITLE
from unknown class to known class

### ISSUE THREAD

**Issue by xiaozhen18239228065** [JosephKJ/OWOD#2]
Hello, I would like to ask, how do you turn an unknown class into a known class? Does it need to be labeled manually?

**Comment by JosephKJ** [comment]
Hi @xiaozhen18239228065, 

Thank you for your nice question. We do expect that the true labels to the unknown instances will become available eventually. In this work, we do expect a human to label it. You can refer to the top part of Figure 2 for clarity. 

Hope this helps, please re-open this issues if you any further queries. 

Thanks!

**Comment by d12306** [comment]
@JosephKJ , in your implementation, did you just use the ground truth of the unknown classes instead of labelling them by humans? I guess you are doing this in code.

**Comment by JosephKJ** [comment]
Yes @d12306. Thats correct.
