### ISSUE TITLE
Problems about ablation experiments and Oracle

### ISSUE THREAD

**Issue by moyoung1996** [JosephKJ/OWOD#20]
Thanks for your great paper! I have some questions about the paper.
1.What does Oracle actually mean? Is it an existing detector or something else? I cannot find any paper about it.
2.Row 4 of ablation experiments(Table 4) shows that only ALU can have a good effect on experiments. How it works without contrastive clustering?

**Comment by JosephKJ** [comment]
Hi @moyoung1996, thank you for your kind words.

1. What does Oracle actually mean? Is it an existing detector or something else? I cannot find any paper about it.
- As mentioned in Sec 5.3: "An ‘Oracle’ detector has access to all known and unknown labels at any point, and serves as a reference."

2. Row 4 of ablation experiments(Table 4) shows that only ALU can have a good effect on experiments. How it works without contrastive clustering?
- The RPN proposals are auto-labelled based on the objectness measure. Please find more info in Sec 4.2. Contrastive clustering is not a pre-req for ALU.
