### ISSUE TITLE
Cuda error

### ISSUE THREAD

**Issue by AmingWu** [JosephKJ/OWOD#23]
Dear Authors,

When I run your code, there is an error about cuda.
![QQ截图20210326222538](https://user-images.githubusercontent.com/38445175/112660416-63755200-8e90-11eb-945d-049e994a934b.png)

CUDA error: invalid device function (ROIAlign_forward_cuda at ....)

**Comment by JosephKJ** [comment]
Which CUDA version are you using?

**Comment by JosephKJ** [comment]
Kindly reopen if you have not resolved the issue.
