### ISSUE TITLE
iOD

### ISSUE THREAD

**Issue by Lily19970207** [JosephKJ/OWOD#24]
Hi @JosephKJ ,I wanna train an incremental objects detection model  . I want to know which YAML file i should use step by step.

I have trained a model in the execution order - \iOD\19_p_1\base_19_train.yaml  -> \iOD\19_p_1\next_1_train_with_ud.yaml.
But it can't detect objects in PREV_INTRODUCED_CLS .

THANKS!

**Comment by JosephKJ** [comment]
Your order is indeed correct. But, there is an additional fine-tuning step too. So, to summarize:

 \iOD\19_p_1\base_19_train.yaml -> \iOD\19_p_1\next_1_train_with_ud.yaml ->  \iOD\19_p_1\ft_with_unk.yaml

**Comment by wyman123** [comment]
> Your order is indeed correct. But, there is an additional fine-tuning step too. So, to summarize:
> 
> \iOD\19_p_1\base_19_train.yaml -> \iOD\19_p_1\next_1_train_with_ud.yaml -> \iOD\19_p_1\ft_with_unk.yaml
Thank you for you amazing works. However, I have two problems:

1. Should I change the WEIGHT of \next_1_train_with_ud.yaml to the final model of base_19_train. Similarly, change the WEIGHT of ft_with_unk to the final model of next_1_train_with_ud during training?
2. Should I turn on the ENABLE_CLUSTERING or ENABLE_THRESHOLD_AUTOLABEL_UNK? I found that they are switched off in almost all configs in iOD

**Comment by JosephKJ** [comment]
Kindly re-open if required.

**Comment by mmaaz60** [comment]
Any plan to release 

> Your order is indeed correct. But, there is an additional fine-tuning step too. So, to summarize:
> 
> \iOD\19_p_1\base_19_train.yaml -> \iOD\19_p_1\next_1_train_with_ud.yaml -> \iOD\19_p_1\ft_with_unk.yaml

Any plan to release the `run.sh` script to reproduce the iOD results?
