### ISSUE TITLE
about visualise_detections.py  No such file or directory  /home/fk1/workspace/OWOD/output/t1_clustering_val/energy_dist_' + str(20) + '.pkl

### ISSUE THREAD

**Issue by liuhaiyang2018** [JosephKJ/OWOD#29]
Hi, Thanks for your excellent work!

How to run visualise_detections.py?

I run the code visualise_detections.py find the file is /home/fk1/workspace/OWOD/output/t1_clustering_val/energy_dist_' + str(20) + '.pkl "" missin?
I want to see an unknown tag in an image?

**Comment by ccblublu** [comment]
you should run train_net.py t*_val.yaml first

**Comment by JosephKJ** [comment]
@ccblublu is correct. Please read through [replicate.sh](https://github.com/JosephKJ/OWOD/blob/master/replicate.sh), if that helps. 

Re-open this issue if required.

**Comment by lcb1225** [comment]
> I run replicate.sh successfully and t*_val.yaml but still t1_clustering_cal is not created.

I also encountered the same problem, have you solved it?
