### ISSUE TITLE
Problem about unknown classes

### ISSUE THREAD

**Issue by GuitarZH** [JosephKJ/OWOD#3]
Thanks for your excellent work!
I really want to know how to detect or segment unknown classes using a custom dataset. Because I'm new to this kind of problem, can you give me some advice?

**Comment by JosephKJ** [comment]
Hi @GuitarZH,

You might have to add your own custom data-loader. 

Thanks!

**Comment by GuitarZH** [comment]
Thank you for your advice.

**Comment by zhanghaozhe23** [comment]
> Thank you for your advice.

Have you solved this problem？
