### ISSUE TITLE
Pretrained models are difficult to download

### ISSUE THREAD

**Issue by CuberrChen** [JosephKJ/OWOD#30]
hi! It's a great job. so i want to start a quick test. Is there a pre-training model quick download link？The data of the link you provided is too large（more than 39G）! 
In addition, I noticed that the energy distribution of the set needs to be verified in the test code. Does this mean that we still need a specific data set, rather than being able to detect any open world?

**Comment by JosephKJ** [comment]
@CuberrChen : Sorry, we have provided all the trained model as is. We dont plan to chunk it into smaller files. 

ORE is trained on data from VOC and COCO. Please read Sec 5.1 of the paper.

**Comment by JosephKJ** [comment]
Please re-open this issue if required. Thanks!
