### ISSUE TITLE
What is the order in which I should use the configuration files in the T1 ~ T4 experiments?Looking forward to your reply!!

### ISSUE THREAD

**Issue by LoveIsAGame** [JosephKJ/OWOD#33]
![image](https://user-images.githubusercontent.com/49852180/114358680-beec5300-9ba5-11eb-90d8-3d9bbdea5df3.png)

**Comment by 1170300714** [comment]
Same question too. Looking forward to your reply

**Comment by JosephKJ** [comment]
Please refer [run.sh](https://github.com/JosephKJ/OWOD/blob/master/run.sh)
