### ISSUE TITLE
Reason for the slow response last month

### ISSUE THREAD

**Issue by JosephKJ** [JosephKJ/OWOD#35]
Hi all, 

My apologies for the slow response during April 2021. I was seriously hospitalized with COVID pneumonia. I lost 20 % of my lungs to the virus. I am improving now. Please find the discharge summary attached along, if that helps you to understand better. 

[discharge_summary.pdf](https://github.com/JosephKJ/OWOD/files/6445837/discharge_summary.pdf)

Thanks,
Joseph

**Comment by qianyizhang** [comment]
stay strong!
