### ISSUE TITLE
Some question about Energy Based Unknown Identifier

### ISSUE THREAD

**Issue by wangjue-wzq** [JosephKJ/OWOD#36]
Hello! I am very interested in this paper, but I do not quite understand the Energy Based Unknown Identifier. These energy values are calculated from the output of the classifier. What is the purpose of using the energy values to distinguish whether the label is unknown or not? The label of the target is determined by the training set. What is the purpose of the judgment here?

**Comment by JosephKJ** [comment]
Hi @wangjue-wzq, 

>What is the purpose of using the energy values to distinguish whether the label is unknown or not? The label of the target is determined by the training set.

Please note that not all unknown data is labelled in the training set. Hence we need a mechanism to automatically identify unknowns. Energy Based Unknown Identifier is used for that. 

Kindly re-open the issue if we want to discuss more. Thank you.
