### ISSUE TITLE
[Resolved] Discrepancy in t*_ft.txt

### ISSUE THREAD

**Issue by PeizeSun** [JosephKJ/OWOD#37]
Thanks for your great work ! 

However, I run the released code but the performance is behind the reported performance in the paper. The first row is the reported performance, the second is my performance. I didn't change any code.
![image](https://user-images.githubusercontent.com/40374966/117645442-2f928980-b1bd-11eb-91ac-6c162802ead1.png)

Meanwhile, I find the data split in your logs is different from the released data split in the google drive.
For task 2 finetune, the first image is data split in your logs, the second is that in the google drive. They are apparently different.
![image](https://user-images.githubusercontent.com/40374966/117646037-e3941480-b1bd-11eb-9cad-f205a34fdbb5.png)
![image](https://user-images.githubusercontent.com/40374966/117646161-09211e00-b1be-11eb-92d0-12e60fc60ebe.png)

Looking forwards your reply.

**Comment by JosephKJ** [comment]
Dear @PeizeSun : I cannot thank you enough for noticing this discrepancy. Apparently, [t2_ft.txt](https://github.com/JosephKJ/OWOD/blob/master/datasets/OWOD_imagesets/t2_ft.txt) was a version that I had used to run an ablation. I have updated the same now. Can you please try now? Unfortunately, I dont have the exact same file with me (the machine on which I ran these is now decommissioned, and I had missed to backup it.), but the current files would suffice. 

Please do try it out and let me know. 

Thanks,
Joseph

**Comment by JosephKJ** [comment]
There is no fine-tuning step required for Task 1. There is nothing like forgetting there. We are learning all the VOC classes in Task 1. Please let me know why you think that t1_ft is necessary.

**Comment by JosephKJ** [comment]
Ah, you might be referring to the old version of run.sh, @LoveIsAGame. Kindly pull the latest tip.

**Comment by LoveIsAGame** [comment]
Yes, I didn't notice you made a change to run.sh two hours ago. Thanks @JosephKJ

**Comment by LoveIsAGame** [comment]
@JosephKJ   In Task1, I am using 1 GPU, so I set BASE_LR to 0.0025 and here is my result.I don't know what went wrong.
The configuration files are executed in the order t1_train t1_val t1_test.
![image](https://user-images.githubusercontent.com/49852180/117979163-352ad380-b365-11eb-89b5-81318584470b.png)
![image](https://user-images.githubusercontent.com/49852180/117979266-4bd12a80-b365-11eb-95c0-c3bc11054733.png)

**Comment by JosephKJ** [comment]
Hi @LoveIsAGame : You need to run it for 8x more iterations as you are running on a single GPU. Please refer to the official Detectron 2 [spec](https://github.com/facebookresearch/Detectron/blob/master/configs/getting_started/tutorial_8gpu_e2e_faster_rcnn_R-50-FPN.yaml#L14). This [issue](https://github.com/facebookresearch/Detectron/issues/530) might also be helpful.

**Comment by dyabel** [comment]
Hi, the new t2_ft.txt is still different from that used in models_backup/t2_ft.The prior contains  1743 images and the latter contains 386. Could you provide the t2_ft.txt which is used to train the model in models_backup? Thx

**Comment by JosephKJ** [comment]
Can you copy over <owod_folder>/datasets/OWOD_imagesets/ to  <owod_folder>/datasets/VOC2007/ImageSets/Main and try? Please ensure that you are on the latest commit of the code. Thanks!

**Comment by dyabel** [comment]
> Can you copy over <owod_folder>/datasets/OWOD_imagesets/ to <owod_folder>/datasets/VOC2007/ImageSets/Main and try? Please ensure that you are on the latest commit of the code. Thanks!
Yes, I have updated the latest t2_ft.txt which has 1743 images, is that right? but the log.txt of t2_ft in your google drive owod_backup shows there are only 386 images. 
![image](https://user-images.githubusercontent.com/52541024/118435937-7844c800-b712-11eb-8028-07dd78680dde.png)
![image](https://user-images.githubusercontent.com/52541024/118436000-914d7900-b712-11eb-89db-67d9153ddce7.png)

**Comment by JosephKJ** [comment]
There is some confusion here: 

1) t2_ft.txt in owod_backup contains 1665 images and not 386 (Please refer to the screenshot in the first comment in this thread by PeizeSun)
2) I believe 386 is what you got after running the previous version of t2_ft.txt 
3) If you run the latest t2_ft.txt, you will get 1743 images. Please find my log below:

<img width="886" alt="Screenshot 2021-05-17 at 10 58 05 AM" src="https://user-images.githubusercontent.com/4231550/118436632-c3ed7680-b6fe-11eb-8298-08a0b8e6476a.png">

**Comment by JosephKJ** [comment]
Kindly reopen if the issue persists.
