### ISSUE TITLE
Unknown classes

### ISSUE THREAD

**Issue by fuchao01** [JosephKJ/OWOD#38]
Can the energy obtained by the unknown category be effectively clustered? Can cluster unknown categories into the same cluster

**Comment by fuchao01** [comment]
What is the data storage format of the queues_tsne.pkl file

**Comment by JosephKJ** [comment]
Hi @fuchao01 ,



> Can the energy obtained by the unknown category be effectively clustered? Can cluster unknown categories into the same cluster

Yes, this is evident from the tsne and Fig.3

>What is the data storage format of the queues_tsne.pkl file

It is created from the feature in the following [commented out code](https://github.com/JosephKJ/OWOD/blob/9b56fdf1d37c15109f17be36806b72e565ec0647/tools/plot_tsne.py#L98).

Kindly reopen for more discussion.

**Comment by fuchao01** [comment]
Does the tsne and Fig.3 use the features of the logit layer to do clustering?

**Comment by fuchao01** [comment]
use the [https://github.com/JosephKJ/OWOD/blob/45da4b5cd09786d1d26cb11617bed2d77f2118e3/detectron2/modeling/roi_heads/roi_heads.py#L450](features) of the logit layer to do clustering?

**Comment by JosephKJ** [comment]
Yes, it uses features from the RoI head.

**Comment by fuchao01** [comment]
Isn't this the 2048-dimensional feature vector mentioned in the paper?

**Comment by JosephKJ** [comment]
Yes. It is just a function which is called appropriately.

**Comment by lsqxxx** [comment]
Can you point out where the energy based models is? Thanks!
