### ISSUE TITLE
Same START_ITER values in t*_train.yam and t*_ft.yaml

### ISSUE THREAD

**Issue by mmaaz60** [JosephKJ/OWOD#40]
Hi,

I noticed that the value of `START_ITER` is the same in all corresponding `train` and `ft` configs. For example, it is `START_ITER: 18000` in both `t2_train.yaml` and `t2_ft.yaml`. As per the script [run.sh](https://github.com/JosephKJ/OWOD/blob/master/run.sh), the finetuning (`t*_ft.yaml`) is using the weights generated from the corresponding `t*_train.yaml` as starting point, so the `START_ITER` shouldn't be the same in both files. Please guide.

Thanks

**Comment by JosephKJ** [comment]
Hi Maaz, 

The START_ITER that you are referring to is the iteration from which we start the clustering process. Kindly note that we dont do clustering while finetuning. Kindly see [this flag](https://github.com/JosephKJ/OWOD/blob/master/configs/OWOD/t2/t2_ft.yaml#L15). 

I am afraid that you are confusing this with [MAX_ITER](https://github.com/JosephKJ/OWOD/blob/master/configs/OWOD/t2/t2_ft.yaml#L9), which controls the number of iterations that the model is trained for. 

Kindly let me know whether this clarifies your doubt. 

Thanks,
Joseph

**Comment by mmaaz60** [comment]
Thank you for your reply. It clarifies my doubt.
