### ISSUE TITLE
Error while training for task 2 - UnboundLocalError: local variable 'length' referenced before assignment

### ISSUE THREAD

**Issue by rush2406** [JosephKJ/OWOD#41]
Hi,

I'm facing the following error while training for task 2 - 
![error](https://user-images.githubusercontent.com/29939341/118948502-6315a680-b969-11eb-8210-24e2cc4e5fb2.png)

Due to this error, I'm unable to start the training for task 2. I would really appreciate if you could help regarding this error.

**Comment by mmaaz60** [comment]
Hi @rush2406,

Please check this https://github.com/JosephKJ/OWOD/pull/42.

**Comment by rush2406** [comment]
Thanks @mmaaz60, it worked!

**Comment by JosephKJ** [comment]
Apparently, this happens because you did change the number of iterations that you used for training Task 1 from 18000 to 36000, but did not update the Task 2 training with this info:
```
OWOD:
  CLUSTERING:
    START_ITER: 18000 ---change-to---> 36000
```
