### ISSUE TITLE
How to build the environment on RTX3090?

### ISSUE THREAD

**Issue by LeryLee** [JosephKJ/OWOD#43]
I followed your settings:
```
python 3.6
cuda 10.2
nvcc 10.2
pytorch 1.6.0
```

But I can't install detectron2, I searched many many solutions, but can't make it work.

Sometime it seems to install detectron2 successfully, but I got the error just like #10 
```
KeyError: 'Non-existent config key: OWOD
```

Then I re-build the detectron2 from the repo, but I got:
```
ValueError: Unknown CUDA arch (8.6) or GPU not supported
```

I submit an issue in the original detectron2 repo: 
https://github.com/facebookresearch/detectron2/issues/3076

And now I just want to know what is your hardware and software  environment in detail, I want to locate where is wrong,
I struggle on this for a whole day, please help me, thank you!

**Comment by JosephKJ** [comment]
It seems that  cuda 10.2 cannot support your GPU. Please see [this](https://stackoverflow.com/a/66974215/2006462). I have used  P100s and V100s. 

Please reopen this issue for further discussions.
