### ISSUE TITLE
Why use the proposal of an unknown class to regress the gt box of a known class

### ISSUE THREAD

**Issue by fan945327815** [JosephKJ/OWOD#44]
Thanks for your greate job! 
I don't know if I understand correctly.  In roi_head stage, is it reasonable to use the proposal of the unknown class to regress the gt box of the known class with the lowest IOU

**Comment by dyabel** [comment]
> Thanks for your greate job!
> I don't know if I understand correctly. In roi_head stage, is it reasonable to use the proposal of the unknown class to regress the gt box of the known class with the lowest IOU

I am also confused about this

**Comment by JosephKJ** [comment]
The proposals that are auto-labelled as unknowns are used only in the contrastive clustering. It is used to learn the classification/regression head. Does this resolve the confusion?

Please re-open this issue for more discussion.

**Comment by TabGuigui** [comment]
hi there,
The proposals that are auto-labelled as unknowns are still used to train the regression head in the code? Is there something improper that the unknown proposals have a corresponding gt boxes to regress?
