### ISSUE TITLE
Can I know the detailed division of data set？

### ISSUE THREAD

**Issue by liMike1998** [JosephKJ/OWOD#45]
First of all, thank you for your work. I know that the data set is composed of coco and VOC, which is divided into four parts. Then I want to know whether the final format of the data in these four parts is unified into VOC format? And what is the composition of the whole data set? Thank you for your reply

**Comment by JosephKJ** [comment]
>Then I want to know whether the final format of the data in these four parts is unified into VOC format?

 Yes, the COCO annotations were converted to the VOC format using [this](https://github.com/JosephKJ/OWOD/blob/master/datasets/coco_utils/coco_annotation_to_voc_style.py) script. 

>And what is the composition of the whole data set? 

Please refer to Table 1 of the paper. If you need more information, please let me know. I will brief you on more specifics. 

Please reopen this issue for more discussions if required.
