### ISSUE TITLE
iOD: 10-10

### ISSUE THREAD

**Issue by CanPeng123** [JosephKJ/OWOD#46]
Hi @JosephKJ, I want to train an incremental detection model for the 10+10 experiment on the VOC dataset. May I know what is the order for using the YAML files step by step? 

I have trained the model in the order - \iOD\10_p_10\base_10_train.yaml -> \iOD\10_p_10\next_10_train_with_unk_detection.yaml. However, the results show catastrophic forgetting. 

Would it possible for you to release the run.sh for the experiments on the VOC dataset? 

Thank you very much.

**Comment by JosephKJ** [comment]
I dont have the exact run files with me. I will update this thread when I have the run.sh ready. 

Thank you.

**Comment by UnityBoy** [comment]
> 

Hi,Dear Peng, May know did it work finally ?

**Comment by UnityBoy** [comment]
@CanPeng123

**Comment by JosephKJ** [comment]
Hi @UnityBoy : If you are only interested in Incremental Object Detection, you may have to consider this recent work. We have released the exact training configurations, logs and trained models for all three settings there: https://github.com/JosephKJ/iOD
