### ISSUE TITLE
Cannot find t1_ft folder in models_backup folder

### ISSUE THREAD

**Issue by Arpitrf** [JosephKJ/OWOD#48]
After downloading the owod_bakcup.zip provided by you and unzipping it, I get the following folders - 
![Screenshot 2021-06-10 at 1 18 59 PM](https://user-images.githubusercontent.com/14124093/121486924-38aa8c80-c9ef-11eb-87bd-ac89806723f6.png)
However, in your t1_test.yaml you have weights in a folder name "t1_ft" (following image) which as you can see is not there in the above image
![Screenshot 2021-06-10 at 1 19 25 PM](https://user-images.githubusercontent.com/14124093/121487101-6263b380-c9ef-11eb-8f1d-db57705f6275.png)
Request your assistance.

**Comment by JosephKJ** [comment]
Hi Arpit, 

The config files should have had been pointing to `t1_clustering_with_save`. I have updated it. Kindly use the latest tip. 

Kindly use [replicate.sh](https://github.com/JosephKJ/OWOD/blob/master/replicate.sh) to replicate the results. 

Please reopen this bug for more discussions. 

Thanks,
Joseph
