### ISSUE TITLE
Problem about training schedule

### ISSUE THREAD

**Issue by GuitarZH** [JosephKJ/OWOD#5]
Hello @JosephKJ,
I am confused about the T1~T4 training schedule. There are many training commands in the run.sh, and I have tried to run some experiments. However, I still do not understand the meaning of YAML filenames and which YAML file I should use in each task. Can you release a shell script for reproduction? 
Thank you very much!

**Comment by ShuoYang-1998** [comment]
I also have the same confusion. If I want to train the T3, should I have to train T1 and T2 models in advance and save the weights? Additionally, should I have to download the provided dataset or just use the originally coco/voc with your provided split txt file?
Thanks!

**Comment by GuitarZH** [comment]
Hi @ShuoYang-1998,
I have downloaded the provided dataset "JPEGImages", I think it consists of voc2007~voc2011 and coco, which is inconsistent with voc2007 + coco mentioned in the paper. In addition, have you tested the training checkpoint using the visualise_detections.py?

**Comment by JosephKJ** [comment]
If I want to train the T3, should I have to train T1 and T2 models in advance and save the weights?

> Yes.


Additionally, should I have to download the provided dataset or just use the originally coco/voc with your provided split txt file?

> You can try that. I have basically collapsed every VOC and COCO images and annotations into a single folder. Moving these images across might be time consuming for you, so I have shared it as a single zip file. 


In addition, have you tested the training checkpoint using the visualise_detections.py?

> No, `visualise_detections.py` was not used. 


However, I still do not understand the meaning of YAML filenames and which YAML file I should use in each task.

> Do consider the config files under `configs/OWOD`. Each t* folder is for each task. Inside use the files as follows: train -> val

Can you release a shell script for reproduction?

> Sure. Please excuse me some time to sought out some other compelling things.

**Comment by GuitarZH** [comment]
> In addition, have you tested the training checkpoint using the visualise_detections.py?
> 
> > No, `visualise_detections.py` was not used.
Maybe I misunderstand something. So which test script is used for visualising the unknown class, as in readme?
