### ISSUE TITLE
About the Oracle setting in open world object detection task

### ISSUE THREAD

**Issue by csuhan** [JosephKJ/OWOD#51]
@JosephKJ Thank you for your great work. 

Can you tell me whether the `tx_train_with_ukn.yml` config is the setting of `Oracle` in Tab. 2? Does it need other datasets than `tx_voc_coco_2007_val_with_known_and_unk`?

Using these configs, I can not reproduce the results.
The results in the paper:
![image](https://user-images.githubusercontent.com/17927516/123917365-48493f80-d9b5-11eb-8211-be69645d572d.png)
and reproduced:
![image](https://user-images.githubusercontent.com/17927516/123917799-c60d4b00-d9b5-11eb-8e43-40ce8140e334.png)

**Comment by kinivi** [comment]
Hi @csuhan , did you manage to reproduce results?
