### ISSUE TITLE
Understand the log files from reproduced results in Google Drive

### ISSUE THREAD

**Issue by munachisonwadike** [JosephKJ/OWOD#52]
Hello! Thank you so much for the great work and organised repository. I just had a few questions:

After checking the reproduced results in the Googe Drive [t1_final/log.txt], I noticed that the A-OSE for t1 was significantly better, precisely at 7185.0, than the score of 8234 reported in the paper. I was wondering why this higher score was not used?  In addition, I was hoping to ask if we report best results from a single round of training or from an average of multiple rounds?

Looking forward to your reply!
Warm regards,

**Comment by JosephKJ** [comment]
Hey @munachisonwadike : Long time, how are you doing?

Well, you are correct that the reproduced results are much better than what is reported in the paper. It was just that at the point of submission, 8234 was what we could get, but we further improved upon it. All results are from a single run. 

I hope this clarifies your questions, please do reopen this issue if required. Thank you.
