### ISSUE TITLE
How to predict labels of known classes ?

### ISSUE THREAD

**Issue by zhongxiangzju** [JosephKJ/OWOD#54]
Energy Based Unknown Identifier can identify known and unknown classes, but how to decide label of each class belonging to known?

**Comment by JosephKJ** [comment]
If a region proposal has higher likelihood to come from the known Weibull distribution, then we rely on the RoI head classifier's output to classify the proposal into one of the known category. 

Hope this clarifies, please reopen this issue if not. Thank you.
