### ISSUE TITLE
Can i give a label to an  unknown object  during inference time??

### ISSUE THREAD

**Issue by feifeiwei** [JosephKJ/OWOD#58]
Hey, i want to know if the unknown objects can be labelled by human during inference time.

**Comment by JosephKJ** [comment]
Hi @feifeiwei, thank you for your nice question. The unknowns are not labelled immediately after they have been identified, instead we wait for such class instances to come in the data-stream in the future. 

I believe Figure 2 in [this paper](https://arxiv.org/pdf/2102.07848.pdf) tries to do something similar to what you intend. Please take a look at it, if that helps. 

Please do reopen this issue for more discussions. 

Thanks,
Joseph
