### ISSUE TITLE
ImageSets folder

### ISSUE THREAD

**Issue by MatteoT9890** [JosephKJ/OWOD#59]
https://drive.google.com/drive/folders/11bJRdZqdtzIxBDkxrx2Jc3AhirqkO0YV

In this link there are only "Annotations" and "JPEGImages" folders, so when I run the command:

`python tools/train_net.py --num-gpus 4 --dist-url='tcp://127.0.0.1:52125' --resume --config-file ./configs/OWOD/t1/t1_train.yaml SOLVER.IMS_PER_BATCH 8 SOLVER.BASE_LR 0.01 OUTPUT_DIR "./output/t1"`

 I face this error:

```
[...]

  File "/home/mtarantino/OWOD/detectron2/data/datasets/pascal_voc.py", line 81, in load_voc_instances
    with PathManager.open(os.path.join(dirname, "ImageSets", "Main", split + ".txt")) as f

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/VOC2007/ImageSets/Main/t1_train.txt'
```

In fact in the folder `datasets` there is no subfolder called `VOC2007/ImageSets/Main`, while there is a subfolder called `OWOD_imagesets` containing the different TXT files. 

So I wonder what is the strategy to handle correctly the different datasets once downloaded "Annotations" and "JPEGImages" from Google drive link in order to avoid `FIleNotFoundError`? 

Thanks in advance

**Comment by MatteoT9890** [comment]
SOLVED:

Solution:

(1) Create folder `datasets/VOC2007`

(2) Put `Annotations` and `JPEGImages` inside `datasets/VOC2007`

(3) Create folder `datasets/VOC2007/ImageSets/Main`

(4) Put the content of `datasets/OWOD_imagesets` inside  `datasets/VOC2007/ImageSets/Main`

**Comment by JosephKJ** [comment]
Thanks @MatteoT9890! I have updated the README with a link to your comment.

**Comment by poojapbabar** [comment]
we followed ur instructions neatly but also we got the same error.

we gave input as:RE/OWOD-master/tools$ python train_net.py --num-gpus 1 --dist-url='tcp://127.0.0.1:52125' --resume --config-file ./configs/OWOD/t1/t1_train.yaml SOLVER.IMS_PER_BATCH 8 SOLVER.BASE_LR 0.01 OUTPUT_DIR "./output/t1"


error:Command Line Args: Namespace(config_file='./configs/OWOD/t1/t1_train.yaml', resume=True, eval_only=False, num_gpus=1, num_machines=1, machine_rank=0, dist_url='tcp://127.0.0.1:52125', opts=['SOLVER.IMS_PER_BATCH', '8', 'SOLVER.BASE_LR', '0.01', 'OUTPUT_DIR', './output/t1'])
Traceback (most recent call last):
  File "/home/sg/Desktop/ORE/OWOD-master/tools/train_net.py", line 163, in <module>
    launch(
  File "/home/sg/Desktop/ORE/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/home/sg/Desktop/ORE/OWOD-master/tools/train_net.py", line 132, in main
    cfg = setup(args)
  File "/home/sg/Desktop/ORE/OWOD-master/tools/train_net.py", line 124, in setup
    cfg.merge_from_file(args.config_file)
  File "/home/sg/Desktop/ORE/detectron2/detectron2/config/config.py", line 45, in merge_from_file
    assert PathManager.isfile(cfg_filename), f"Config file '{cfg_filename}' does not exist!"
AssertionError: Config file './configs/OWOD/t1/t1_train.yaml' does not exist!



will you please us


Thank You

**Comment by PixelChen24** [comment]
> **SOLVED:**
> 
> Solution:
> 
> (1) Create folder `datasets/VOC2007`
> 
> (2) Put `Annotations` and `JPEGImages` inside `datasets/VOC2007`
> 
> (3) Create folder `datasets/VOC2007/ImageSets/Main`
> 
> (4) Put the content of `datasets/OWOD_imagesets` inside `datasets/VOC2007/ImageSets/Main`
> 
> I suggest you to put this flow inside the README.md!
> 
> Have a nice day!

What will the `JPEGImages` and `Annotations` directory looks like? Does there exist any sub-directories in this directory?
For the lack of access to google drive, I cannot download the whole dataset. Hope for your response, thanks a lot.

**Comment by XuHu0529** [comment]
@PixelChen24 Hi, I cannot download the whole dataset. Could you share me the files? Thanks a lot!

**Comment by chenfangchenf** [comment]
@PixelChen24 Hello, could you let me download the data? Thank you very much！

**Comment by PixelChen24** [comment]
> @PixelChen24 Hello, could you let me download the data? Thank you very much！

Of course, please give me your email so that we can chat via email

**Comment by PixelChen24** [comment]
> @PixelChen24 Hi, I cannot download the whole dataset. Could you share me the files? Thanks a lot!

Of course, please give me your email so that we can chat via email

**Comment by JosephKJ** [comment]
Hello @lxtGH @chenfangchenf @PixelChen24 , Please use this link instead: https://drive.google.com/drive/folders/1S5L-YmIiFMAKTs6nHMorB0Osz5iWI31k?usp=sharing 

(I have updated the first post too)

**Comment by chenfangchenf** [comment]
thank you very much!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JosephKJ/OWOD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 晚上9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JosephKJ/OWOD] ImageSets folder (#59)





 
Hello, Please use this link instead: https://drive.google.com/drive/folders/1S5L-YmIiFMAKTs6nHMorB0Osz5iWI31k?usp=sharing
 
(I have updated the first post too)

**Comment by chenfangchenf** [comment]
thank you very much !
My email is&nbsp; ***@***.***





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JosephKJ/OWOD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 晚上9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JosephKJ/OWOD] ImageSets folder (#59)





  
@PixelChen24 Hello, could you let me download the data? Thank you very much！
  
Of course, please give me your email so that we can chat via email

**Comment by JiuqingDong** [comment]
> > @PixelChen24 Hi, I cannot download the whole dataset. Could you share me the files? Thanks a lot!
> 
> Of course, please give me your email so that we can chat via email

could you tell me how to download the dataset? This is my email dongjiuqing1996@gmail.com
Thank you very much!

**Comment by PixelChen24** [comment]
> > @PixelChen24您好，我无法下载整个数据集。你能把文件分享给我吗？多谢！
> 
> Me too
I have written a blog on how to download huge datasets on Google Drive for Chinese developers or those who have trouble accessing Google, you can follow [this](https://www.zhihu.com/question/370464588/answer/2789649195)

**Comment by functail** [comment]
Helloooooooooo friends from china mainland! 
Here is a solution for downloading data effectively:
https://github.com/JosephKJ/OWOD/issues/122

**Comment by nikoubaibai** [comment]
Use”python tools/train_net.py --num-gpus=1 --config-file=./configs/OWOD/iOD/all_20_train.yaml“to it report an error

**Comment by zyj101511** [comment]
> > [@JosephKJ](https://github.com/JosephKJ) Hi! Jose. For the lack of access to google drive, I cannot download the whole dataset. Hope for your response, thanks a lot. Could you please update the download link?
> 
> 兄弟，我已经下载了这个数据并且存在阿里云盘了，可惜阿里云盘无法共享压缩包文件，你要是真的要的话我可以扫码授权登录你下载

兄弟数据集你那里还有吗

**Comment by nikoubaibai** [comment]
他这个数据集网上都有啊，我是女的



发自我的iPhone


------------------ Original ------------------
From: zhangyan101511 ***@***.***&gt;
Date: Sat,May 24,2025 10:11 PM
To: JosephKJ/OWOD ***@***.***&gt;
Cc: nikoubaibai ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [JosephKJ/OWOD] ImageSets folder (#59)



zhangyan101511 left a comment (JosephKJ/OWOD#59)
   
@JosephKJ Hi! Jose. For the lack of access to google drive, I cannot download the whole dataset. Hope for your response, thanks a lot. Could you please update the download link?
  
兄弟，我已经下载了这个数据并且存在阿里云盘了，可惜阿里云盘无法共享压缩包文件，你要是真的要的话我可以扫码授权登录你下载
  
兄弟数据集你那里还有吗

**Comment by 17630567279** [comment]
@PixelChen24 
可以联系发我一份数据集吗，我的邮箱是hh528658@163.com，非常感谢你！！！

**Comment by swu065683-web** [comment]
@PixelChen24 我也想复现论文的效果，可以联系我发一份数据集和模型吗？或者给个您之前下载到的链接，我邮箱是lmqismmmq@163.com，非常感谢您！！！！！

**Comment by Karthikpasupuleti11** [comment]
I am trying to access the folder(drive link- https://drive.google.com/drive/folders/1S5L-YmIiFMAKTs6nHMorB0Osz5iWI31k) using my account (pasupuletikarthik11@gmail.com), but the link appears to be empty on my end.Could you please double-check the sharing permissions to ensure my email address has "Viewer" or "Editor" access
