### ISSUE TITLE
Bbox supervision signal for unknown class

### ISSUE THREAD

**Issue by liuchang8am** [JosephKJ/OWOD#6]
Are ground-truth bounding boxes for unknown class utilized as supervision signal during training?

**Comment by JosephKJ** [comment]
No. They are not.

**Comment by liuchang8am** [comment]
> No. They are not.

Thanks!

**Comment by LoveIsAGame** [comment]
@liuchang8am
@JosephKJ @salman-h-khan 
  I have the same problem.How does the unknown class participate in network training if the unknown class tag is not used in the training process?
Looking forward to your answer!

**Comment by JosephKJ** [comment]
@LoveIsAGame: Energy based models have the implicit capability to learn an energy manifold with low energy values for known known data only. Hence an unknown instance at validation/test time will have low energy as seen from Figure 3. Kindly refer to Sec 4.3 for more details.

**Comment by LoveIsAGame** [comment]
@liuchang8am @JosephKJ @salman-h-khan 
I still don't quite understand.We use the program to find the unknown object, but there is no GT of the position object, how do we do the linear regression of the unknown object.

They simply recognize the presence of an unknown object, but they don't know its authenticity.I don't know if this is correct?

**Comment by lsqxxx** [comment]
Can you point out where the energy based models is? Thanks!

**Comment by jinweiisgreat** [comment]
> 
@LoveIsAGame Hi！Same question about how to localize unknown instances. Are you solved?
