### ISSUE TITLE
Why is there a certain difference in recurring results？

### ISSUE THREAD

**Issue by yuandhu** [JosephKJ/OWOD#63]
Except for the inconsistent number of GPUs used, the other configurations are the same. Regarding the known classes, I got similar results to the author. However, on the A-OSE measurement, my results are quite different from those in the paper. Below are my recurring results for the four tasks. I hope the author can answer my question. Thanks!
![image](https://user-images.githubusercontent.com/48075438/132932820-d5b6efa3-1fa2-4990-8d1c-4e9ab7d4c28a.png)

**Comment by JosephKJ** [comment]
Please note that other have independently been able to reproduce the results ([link](https://github.com/JosephKJ/OWOD/issues/18#issuecomment-840943128)). WI is bit noisy, but other metrics should match up. Have you tried scaling the hyper params according to the discussion [here](https://github.com/JosephKJ/OWOD/issues/37#issuecomment-839839855)?

**Comment by akshitac8** [comment]
Hello @JosephKJ @yuandhu I was sucessfully able to reproduce the results and also attached the table for the same

<google-sheets-html-origin>

  | ResNet-50 | ORE (paper) |   | 56.34 |   | 8234 | 0.02193 | 52.37 | 25.58 | 38.98 |   | 7772 | 0.0154 | 37.77 | 12.41 | 29.32 |   | 6634 | 0.0081 | 30.01 | 13.44 | 26.66
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | ORE (retrained) |   |  |55.86 |  | 6390 | 0.04867 | 52.36 | 25.04 | 38.71 |   | 7635 | 0.0387 | 37.52 | 12.28 | 29.11 | 0.11 | 6151 | 0.0275 | 29.63 | 12.82 | 25.43
  |  | Recall |  | 71.92 |   |   |   | 71.74 | 46.53 | ` |  |   |   | 57.12 | 33.69 | 49.31 | 9.11 |   |   | 51.99 | 36.17 | 48.03

**Comment by yuandhu** [comment]
> Hello @JosephKJ @yuandhu I was sucessfully able to reproduce the results and also attached the table for the same
> 
>  	ResNet-50	ORE (paper)	 	56.34	 	8234	0.02193	52.37	25.58	38.98	 	7772	0.0154	37.77	12.41	29.32	 	6634	0.0081	30.01	13.44	26.66
>  	ORE (retrained)	 		55.86		6390	0.04867	52.36	25.04	38.71		7635	0.0387	37.52	12.28	29.11	0.11	6151	0.0275	29.63	12.82	25.43
>  		Recall		71.92		 	 	71.74	46.53	`		 	 	57.12	33.69	49.31	9.11	 	 	51.99	36.17	48.03

thank you

**Comment by yuandhu** [comment]
> Please note that other have independently been able to reproduce the results ([link](https://github.com/JosephKJ/OWOD/issues/18#issuecomment-840943128)). WI is bit noisy, but other metrics should match up. Have you tried scaling the hyper params according to the discussion [here](https://github.com/JosephKJ/OWOD/issues/37#issuecomment-839839855)?

thank for you reply！！I aslo have an another question。
In builtin.py . there are 81 (include unknown)categories in total，why only 80 categories in detectron2/config/defaults.py?
i.e. _C.MODEL.ROI_HEADS.NUM_CLASSES = 80
and when label unknown in detectron2/data/build.py/label_known_class_and_unknown ,the unknown class be labeled with
annotation["category_id"] = total_num_class - 1,whcih is the last categories in known class.I can't understand.
that might be a easy problem ,look forward to your reply again~
