### ISSUE TITLE
google drive link limited access ?

### ISSUE THREAD

**Issue by trungpham2606** [JosephKJ/OWOD#7]
@JosephKJ 
Tks for sharing such a great work !
Excuse me but I cant download anything from google drive link you had provided (limited access).

**Comment by JosephKJ** [comment]
Hi @trungpham2606, 

I am afraid that it is not an issue from our end. Please try the link from an incognito / private window. 

Thanks!

**Comment by ShuoYang-1998** [comment]
Hi, when downloading the provided data split, an error message ' Google drive download quota exceed' will be appeared. It might be caused by frequently access to the download link. Can your fix it? Thanks!

**Comment by tanchaow** [comment]
same problems!
