### ISSUE TITLE
compute energy

### ISSUE THREAD

**Issue by WXLL579** [JosephKJ/OWOD#70]
Thanks for your excellent work! I have read your code, but I did not find the code for function E in energy based models (EBMs) , I understand that it may be this formula: Helmholtz free energy formulation

Hoping for your reply~

**Comment by WXLL579** [comment]
I'm not completely sure，but maybe you can check detectron2/engine/train_loop.py at about line 220

**Comment by lsqxxx** [comment]
Excuse me, where is the code about the energy based models? Thank you
