### ISSUE TITLE
Question about the exemplar memory

### ISSUE THREAD

**Issue by luckychay** [JosephKJ/OWOD#71]
![Screenshot from 2021-10-06 09-39-27](https://user-images.githubusercontent.com/55084546/136127230-6b4919bf-1fe6-4bfe-8267-d47f31cb3481.png)

Thank you for your amazing job. When I read the paper, I got a question about the  exemplar memory.

As you said in the Supplementary Material of the paper, the exemplar memory takes about 34MB. Does it mean the extra size of the model  to avoid forgetting? But the number of classes is varibale, how many classes is 34MB  for?

**Comment by JosephKJ** [comment]
34MB is the size of the exemplar store (when saved to disk) in the 15+5 setting.
