### ISSUE TITLE
How t1_train.txt is generated.

### ISSUE THREAD

**Issue by lxqiaoyixuan** [JosephKJ/OWOD#73]
Hi~ Thanks for your great work!

I'd like to know how the t1 training set (t1_train.txt) is generated, as far as I know, t1_train.txt has 16551 images which come from VOC dataset and COCO dataset, could you please provide create_t1_imageset.py [(like scripts for t2-t4)](https://github.com/JosephKJ/OWOD/tree/master/datasets/coco_utils) or a detailed introduction?

Looking forward to your early reply. @JosephKJ @salman-h-khan Thank you!~

**Comment by JosephKJ** [comment]
Hi @lxqiaoyixuan,

Thanks for your interest. As explained in the paper, the first task data is VOC dataset as is. No change to VOC at all. Hope this helps, if not, please reopen this issue.

<img width="381" alt="Screenshot 2021-12-04 at 12 08 14 PM" src="https://user-images.githubusercontent.com/4231550/144700370-8eee027e-311a-42d8-8e77-04db78acda71.png">

Thanks!

**Comment by JiweiMaster** [comment]
Hi, guy~
the first task (t1) data is VOC dataset as is, so all test images are knowned classes, I'm confused that how can we calculate WI metrics for t1 task, because need to calcutae precision of Known classes and Unknown classes?
Thanks!
