### ISSUE TITLE
万事俱备只欠东风

### ISSUE THREAD

**Issue by Allenstin** [JosephKJ/OWOD#75]
首先，感谢作者作出的重大贡献。作者可能看不懂中文，没关系，自我吐槽下好了。
我已经在rtx3090上把环境装好了，数据也在谷歌云盘上下载好了，测试过可以进行训练。万事俱备，只欠东风。
我现在困惑的是不知道怎么去根据作者提供的数据集进行训练。我对这些数据怎么分组，怎么训练，为何这么分组，以及怎么使用自己的数据进行训练等等这些问题都十分困惑。
我看了一些issues, 发现好多人都存在数据训练上的困惑，感觉是作者没有把事情说清楚。而且我还看到有人吐槽说根据作者的代码无法复现论文的结果。不好的消息是，这篇文章雷声大雨点小。但是，我希望是我理解没到位，我希望这个算法是有效的。

**Comment by JosephKJ** [comment]
I am unable to understand.

**Comment by lxtGH** [comment]
@dyabel 老哥 现在还没复现出来么？

**Comment by dyabel** [comment]
> 
已经放弃了，因为有数据泄露，这个方法就是错的，没必要复现了

**Comment by dyabel** [comment]
@lxtGH 已经放弃了，因为存在数据泄露，这篇文章方法就是错的，没必要复现了

**Comment by DeidaraYang** [comment]
@dyabel 但感觉不引入这个validation的话就无法单独测试这个EBUI模块对模型性能的影响了

**Comment by dyabel** [comment]
@DeidaraYang 这个EBUI确实是必要的，但是用到unknown gt还算是open-world吗

**Comment by Usernamezhx** [comment]
@JosephKJ He said he has the problem about the preparing of the his own customer data

**Comment by zxzheng826** [comment]
It seens like the author @JosephKJ has realized the problem of using the validation set to train the energy distributions. In their new work OW-DETR, they mentioned this point. 似乎他们已经意识到这个问题了，最近他们实验室几个作者新提出的OW-DETR工作中有提到这一点疑似数据泄漏的问题。

**Comment by sixzerotech** [comment]
> OW-DETR

这不是自己打自己脸了，这种文章应该撤稿

**Comment by d12306** [comment]
还是不要在这议论了，作者谷歌翻译还是能看得懂的。。。。

**Comment by sixzerotech** [comment]
🤭





------------------ 原始邮件 ------------------
发件人: Xuefeng Du ***@***.***&gt;
发送时间: 2022年2月14日 03:14
收件人: JosephKJ/OWOD ***@***.***&gt;
抄送: 实名冲浪lly ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [JosephKJ/OWOD] 万事俱备只欠东风 (Issue #75)

**Comment by chaochaozouzou** [comment]
> 我最近也做了一些检测未知类的实验，效果还行，大佬们到时候可以瞄一眼，不过我是基于YOLOv5做的，用coco的80类训练，可以一定程度上检测80类之外的物体。 ![96172e01e70f40d9](https://user-images.githubusercontent.com/84908793/164317433-da8b96b6-c1c7-474f-b11a-16c4bb69e3e5.png)

求指教

**Comment by feimadada** [comment]
> 我最近也做了一些检测未知类的实验，效果还行，大佬们到时候可以瞄一眼，不过我是基于YOLOv5做的，用coco的80类训练，可以一定程度上检测80类之外的物体。 ![96172e01e70f40d9](https://user-images.githubusercontent.com/84908793/164317433-da8b96b6-c1c7-474f-b11a-16c4bb69e3e5.png)

怎么做的呀，大佬

**Comment by zhaochunhai** [comment]
> 我最近也做了一些检测未知类的实验，效果还行，大佬们到时候可以瞄一眼，不过我是基于YOLOv5做的，用coco的80类训练，可以一定程度上检测80类之外的物体。 ![96172E01E70F40D9](https://user-images.githubusercontent.com/84908793/164317433-da8b96b6-c1c7-474f-b11a-16c4bb69e3e5.png)

怎么实现的大佬，最近要参加一个比赛，可不可以分享一下思路

**Comment by Allenstin** [comment]
原理是，网络能够学习到通用的前景信息，推理的时候，把前景信息置信度高，而分类信息置信度低的拿出来，就能在一定程度上检测未知物体。&nbsp;


吴阳阳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月25日(星期二) 晚上8:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JosephKJ/OWOD] 万事俱备只欠东风 (Issue #75)





  
我最近也做了一些检测未知类的实验，效果还行，大佬们到时候可以瞄一眼，不过我是基于YOLOv5做的，用coco的80类训练，可以一定程度上检测80类之外的物体。 
  
怎么实现的大佬，最近要参加一个比赛，可不可以分享一下思路
