### ISSUE TITLE
Confusion about the t2_train/t2_ft procedure

### ISSUE THREAD

**Issue by YujunLiao** [JosephKJ/OWOD#76]
Professor Joseph, Thanks for your great work!

Sorry for the interruption, I have read the training log in the models_backup files released in google drive, and I have 2 questions as follow:
    1. According to the log, the whole training process is that: t1_train -> t2_train for 3 times -> t2_ft for 3 times -> t3 _train -> t3_ft -> t4_train -> t4_ft, is it correct? If it is correct, do i also need to run t2_train and t2_ft for three times?
    2. I notice that, when you ran t2_ft for the first time, you got only 386 images and 2390 instances, the detail is shown as follow. 
   
![fig1](https://user-images.githubusercontent.com/37390451/140640268-c1ee5b31-fb77-494f-87c0-3d4d340f452c.png)

but when you ran t2_ft for the second and third time, you got 1665 images and 10054 instances,  the detail is shown as follow.

![fig2](https://user-images.githubusercontent.com/37390451/140640266-dd3d9250-ba59-404a-8260-015976a7e1eb.png)

I check the datasets used for them, they are the same data split, which is t2_voc_coco_2007_ft, so, why the images numbers were different between the first and second/third t2_ft? 
    
 Btw, I have also read issue 67, but I am still in confusion, could you help me? Thank you!

**Comment by JosephKJ** [comment]
Hi @YujunLiao : please refer to [run.sh](https://github.com/JosephKJ/OWOD/blob/master/run.sh), for the commands. The logs are basically accumulations of different runs. The order of commands are in run.sh.
