### ISSUE TITLE
Where is the code of "4.3. Energy based unknown identifier"

### ISSUE THREAD

**Issue by lsqxxx** [JosephKJ/OWOD#78]
Hello, author. First of all, thank you very much. I'd like to ask you about "4.3. Energy based unknown identifier", which contains the code about energy. I can't find it.

**Comment by JosephKJ** [comment]
Hi @lsqxxx,

Saving the data to learn the energy distribution: https://github.com/JosephKJ/OWOD/blob/master/detectron2/modeling/roi_heads/roi_heads.py#L455 (initiated from *_val.yaml)

Learning the energy distribution: https://github.com/JosephKJ/OWOD/blob/master/detectron2/engine/train_loop.py#L172

Using the energy distribution: https://github.com/JosephKJ/OWOD/blob/master/detectron2/evaluation/pascal_voc_evaluation.py#L122 

Thanks,
Joseph
