### ISSUE TITLE
Confusion about output of RPN block

### ISSUE THREAD

**Issue by giangnt071098** [JosephKJ/OWOD#84]
Thank you for your work
I have some confusion about the output of Unknown-aware RPN in your paper.
What is the purpose of RPN block? The loss function for RPN is just calculated between region proposal (that have high objectness scores) and bounding boxes of known objects, and top-k background region proposal is just seemed like ground truth for energy-based classification, is it right? In the inference, unknown objects are region proposals from RPN? please, correct me if I misunderstood. Thank you

**Comment by JosephKJ** [comment]
What is the purpose of RPN block?
> To generate region proposals, that will be further classified by the RoI head. 

The loss function for RPN is just calculated between region proposal (that have high objectness scores) and bounding boxes of known objects
> Yes

and top-k background region proposal is just seemed like ground truth for energy-based classification, is it right?
> No, top-k background region proposal are used in the contrastive clustering component, where it auto-labels these as unknowns, and helps enforce latent separation. 

In the inference, unknown objects are region proposals from RPN?
> No, those region proposals that have higher likelihood to belong to the unknown Weibull distribution is labelled as an unknown object.
