### ISSUE TITLE
AssertionError: Checkpoint detectron2://ImageNetPretrained/MSRA/R-50.pkl not found!

### ISSUE THREAD

**Issue by songchuanle-1** [JosephKJ/OWOD#86]
what do i need to do?

**Comment by CtCCtV** [comment]
You can download it to your local environment instead.

**Comment by Drios-strawberry** [comment]
> what do i need

> 
Have you solved the problem yet?
What did you do to solved it ? What files did you download into the OWOD folder

**Comment by PixelChen24** [comment]
You can download the pkl file [here](https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/MSRA/R-50.pkl). After that, just specify the class path in the config yaml file (MODEL->WEIGHTS)

**Comment by PixelChen24** [comment]
You can download the pkl file [here](https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/MSRA/R-50.pkl). After that, just specify the file path in the config yaml file (MODEL->WEIGHTS)

**Comment by PixelChen24** [comment]
> > what do i need
> 
> > 
> 
> Have you solved the problem yet? What did you do to solved it ? What files did you download into the OWOD folder

You can download the pkl file [here](https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/MSRA/R-50.pkl). After that, just specify the file path in the config yaml file (MODEL->WEIGHTS)
