### ISSUE TITLE
Share file download exceeded quota

### ISSUE THREAD

**Issue by LoveIsAGame** [JosephKJ/OWOD#9]
hi @JosephKJ , I tried to download the file you shared on GD, but it kept reminding me that I had exceeded the download limit and could not download it. Besides, I tried many ways but failed. Could you please share the data again?Or some other way to share it with me.Thank you very much!

**Comment by JosephKJ** [comment]
@LoveIsAGame: this is very weird. Can you think of and suggest any alternate hosting service?

**Comment by LoveIsAGame** [comment]
You can try to reshare, create a new link, and then update @JosephKJ

**Comment by JosephKJ** [comment]
@LoveIsAGame : I have shared another drive link too.
