### ISSUE TITLE
for energy_dist_20.pkl, how to use it in test?

### ISSUE THREAD

**Issue by Drios-strawberry** [JosephKJ/OWOD#94]
when I test the t1_test.yaml after I python 3 t1_val.yaml, it's saying "Energy distribution is not found at ./output/temp_3/energy_dist_20.pkl",but it's also can test. What's more , I think it's may be that i am not place it right，but if I put it，the AP50  be down , but the and Absolute OSE is up, can you tell me why?

**Comment by JosephKJ** [comment]
Please [run these commands](https://github.com/JosephKJ/OWOD/blob/master/run.sh#L18-L20) as is. If you still face the issue, please reopen.
