### ISSUE TITLE
Why not dense unknown boxes？There should be infinite unknown boxes.

### ISSUE THREAD

**Issue by Wulx2050** [JosephKJ/OWOD#97]
Why not dense unknown boxes? In the "A sample qualitative result" example, apples and oranges are marked as unknown to begin with, but why aren't glasses, human ears, eyebrows, hair, clothes, tables, ironwork behind, and even air marked as unknown?

Unknown categories are infinite, and there should be infinite unknown boxes.

Of course, the content of a picture is limited, and it is impossible to contain infinite objects of unknown categories, but the boxes of unknown categories should also be much more than those marked in the picture.

为什么不是密密麻麻的未知框？在“A sample qualitative result”示例中，苹果和橘子开始被标记为未知，但是为什么眼镜、人的耳朵、眉毛、头发、衣服、桌子、后面的铁制品、甚至是空气都没有被标记为未知？

未知类别是无穷个，应该有无穷个未知框才对。

当然，一张图片的内容有限，不可能包含无限个未知类别的物体，但是未知类的框也应该远远比图中标记的要多得多。

A sample qualitative result：
https://camo.githubusercontent.com/48fec353f66f8528547527d6fc598e25cf6c16a4b919f554ed318ebd1ee438e0/68747470733a2f2f6a6f736570686b6a2e696e2f6173736574732f696d672f6f776f642f6578616d706c652e706e67

**Comment by Wulx2050** [comment]
For limited categories of images, we can label them all at once. But for infinite categories of image detection, we should ask this question: will you take a closer look? What else can you see?

Do you really know what this is?

对有限类别的图像，我们可以一次性全部标注。但是对于无限类别的图像检测，也行我们应该这样问：你再仔细看看？你还能看出什么？

你真的知道这是什么吗？

**Comment by buxihuo** [comment]
你真的知道这是什么吗？
哈哈，我就是尝试从这里切入的。

**Comment by Wulx2050** [comment]
Maybe I should consider using [CLIP](https://github.com/openai/CLIP)?

也许我应该考虑使用[CLIP](https://github.com/openai/CLIP)？

**Comment by WeiJiN-UQ** [comment]
> Maybe I should consider using [CLIP](https://github.com/openai/CLIP)?
> 
> 也许我应该考虑使用[CLIP](https://github.com/openai/CLIP)？

If you introduce CLIP， the task could change to an Open-vocabulary object detection task.
如果你引入CLIP的话，是不是就变成Open-vocabulary的问题了？
